export const ServiceList = {
  services: [
    {
      id: 1,
      name: 'Service 1',
      description: 'Description 1',
      price: 100,
      duration: 60,
    },
    {
      id: 2,
      name: 'Service 2',
      description: 'Description 2',
      price: 200,
      duration: 120,
    },
  ],
};

export const PeopleList = {
  people: [
    {
      id: 1,
      name: 'Person 1',
      email: 'Email 1',
      phone: 'Phone 1',
      image:
        'https://cdn.dribbble.com/users/1571365/avatars/normal/ee8b6282c1a154544e839913e311aff0.jpg?1580130916',
      description: 'Description 1',
      location: 'Location 1',
    },
    {
      id: 2,
      name: 'Person 2',
      email: 'Email 2',
      phone: 'Phone 2',
      image:
        'https://cdn.dribbble.com/users/1571365/avatars/normal/ee8b6282c1a154544e839913e311aff0.jpg?1580130916',
      description: 'Description 2',
      location: 'Location 2',
    },
  ],
};

export const LocationList = {
  location: [
    {
      id: 1,
      name: 'Location 1',
      address: 'Address 1',
      city: 'City 1',
      state: 'State 1',
      zip: 'Zip 1',
      country: 'Country 1',
      phone: 'Phone 1',
      email: 'Email 1',
      website: 'Website 1',
      description: 'Description 1',
      image:
        'https://cdn.dribbble.com/userupload/3814579/file/original-ce86d1a028de0c15237ae30bbc7fbd3f.png?compress=1&resize=1504x1128&vertical=center',
      lat: 'Lat 1',
      lng: 'Lng 1',
      timezone: 'Timezone 1',
      currency: 'Currency 1',
      currency_symbol: '$',
      currency_format: 'Currency Format 1',
      currency_code: 'Currency Code 1',
    },
    {
      id: 2,
      name: 'Location 2',
      address: 'Address 2',
      city: 'City 2',
      state: 'State 2',
      zip: 'Zip 2',
      country: 'Country 2',
      phone: 'Phone 2',
      email: 'Email 2',
      website: 'Website 2',
      description: 'Description 2',
      image:
        'https://cdn.dribbble.com/userupload/3814579/file/original-ce86d1a028de0c15237ae30bbc7fbd3f.png?compress=1&resize=1504x1128&vertical=center',
      lat: 'Lat 2',
      lng: 'Lng 2',
      timezone: 'Timezone 2',
      currency: 'Currency 2',
      currency_symbol: '$',
      currency_format: 'Currency Format 2',
      currency_code: 'Currency Code 2',
    },
    {
      id: 3,
      name: 'Location 3',
      address: 'Address 3',
      city: 'City 3',
      state: 'State 3',
      zip: 'Zip 3',
      country: 'Country 3',
      phone: 'Phone 3',
      email: 'Email 3',
      website: 'Website 3',
      description: 'Description 3',
      image:
        'https://cdn.dribbble.com/userupload/3814579/file/original-ce86d1a028de0c15237ae30bbc7fbd3f.png?compress=1&resize=1504x1128&vertical=center',
      lat: 'Lat 3',
      lng: 'Lng 3',
      timezone: 'Timezone 3',
      currency: 'Currency 3',
      currency_symbol: '$',
      currency_format: 'Currency Format 3',
      currency_code: 'Currency Code 3',
    },
    {
      id: 4,
      name: 'Location 4',
      address: 'Address 4',
      city: 'City 4',
      state: 'State 4',
      zip: 'Zip 4',
      country: 'Country 4',
      phone: 'Phone 4',
      email: 'Email 4',
      website: 'Website 4',
      description: 'Description 4',
      image:
        'https://cdn.dribbble.com/userupload/3814579/file/original-ce86d1a028de0c15237ae30bbc7fbd3f.png?compress=1&resize=1504x1128&vertical=center',
      lat: 'Lat 4',
      lng: 'Lng 4',
      timezone: 'Timezone 4',
      currency: 'Currency 4',
      currency_symbol: '$',
      currency_format: 'Currency Format 4',
      currency_code: 'Currency Code 4',
    },
  ],
};
